# stop all the docker containers that are running ...
- name: docker stop containers
  when: containers_running.rc == 0
  shell: docker stop $(docker ps -aq)
  # ignoring error outputs
  ignore_errors: yes
# remove the containers
- name: docker remove containers
  when: containers_running.rc == 0
  shell: docker rm $(docker ps -aq)
  # ignoring error outputs
  ignore_errors: yes
# run a nginx docker container
- name: docker run nginx lb
  vars:
    - _nginx_lb_path: /etc/nginx/conf.d/default.conf
  shell: |
    docker run \
    --restart always \
    -v {{ nginx_lb_conf_path | default(_nginx_lb_path) }}:/etc/nginx/conf.d/default.conf:ro \
    -p 80:80 \
    -d nginx

# build docker using the docker file and go inside the destination directory
- name: docker build
  vars:
    _docker_app_name: app
  shell:
    cmd: docker build -t {{ docker_app_name | default(_docker_app_name) }} .
    chdir: "{{ dest_dir }}"
# docker run on port 80
- name: docker run app
  vars:
    _docker_app_name: app
  shell: |
    docker run \
    --restart always \
    -p 80:8001 \
    -e PORT=8001 \
    -d {{ docker_app_name | default(_docker_app_name) }}