# check if get-docker.sh script is present.
- name: Verify if get-docker.sh is present
  shell: ls /tmp/ | grep get-docker.sh
  ignore_errors: yes
  register: get_docker

# rc = 0 means present, rc !=0 means NOT present
- debug: msg=”{{ get_docker }}”

# if not, get the url content and put it inside .sh script
- name: Grab Docker Install Script
  when: get_docker.rc !=0
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: 0755
  notify: exec docker script

# check if docker 
- name: Verify Docker Command
  shell: command -v docker >/dev/null 2>&1
  ignore_errors: yes
  register: docker_exists

- debug: msg=”{{ docker_exists }}”

# rc = 0 if it exist, rc !=0 if it do not exist. 
# if it don't exit, install it!
- name: Trigger docker install script if docker not running
  when: docker_exists.rc != 0
  shell: /tmp/get-docker.sh
