# ansible webapps.yaml file.
---
- hosts: webapps
  become: yes
  # do nto gather facts for faster runs
  gather_facts: no
  #vars are the variables used in a template
  vars:
    title: Hello there
    description: Some more news!
  # roles install the nginx found ..\roles\nginx\tasks. I think roles are useless. better use playbook instead.
  roles:
    - ./../roles/nginx
    - ./../roles/docker
  tasks:
    - name: Update Nginx Default Homepage
      # use template to copy files into destination
      template:
        dest: /var/www/html/index.nginx-debian.html
        src: ../templates/nginx.default.html